repos:
  # GitHub Actions workflow validation
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.25
    hooks:
      - id: actionlint
        args: [--verbose]
        files: \.github/workflows/.*\.ya?ml$

  # YAML syntax validation
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [--config-file=.yamllint]
        files: \.ya?ml$
        exclude: ^helm/

  # Shell script validation
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        args: [--severity=warning]
        files: \.(sh|bash)$

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^helm/
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
