apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oomlet.fullname" . }}-config
data:
  application.properties: |
    management.endpoints.web.exposure.include=*
    management.endpoint.health.probes.enabled=true
