apiVersion: v1
kind: Service
metadata:
  name: {{ include "oomlet.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "oomlet.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
