apiVersion: apps/v1
kind: Deployment
metadata:
  name: oomlet
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oomlet
  template:
    metadata:
      labels:
        app: oomlet
    spec:
      containers:
      - name: oomlet
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx400m"
        resources:
{{- toYaml .Values.resources | nindent 10 }}
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3