replicaCount: 1

image:
  repository: ghcr.io/trcjr/oomlet
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "512Mi"
    cpu: "250m"
ingress:
  enabled: false
  className: "nginx"
  host: "oomlet.local"