name: Helm Lint and Package Only

on:
  push:
    branches:
      - helm-lint-only
  workflow_dispatch:

jobs:
  helm:
    name: Helm Lint and Package (No Upload)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Git Short Hash
        id: vars
        run: |
          echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Debug Git Short Hash
        run: echo "SHORT_HASH=${{ steps.vars.outputs.SHORT_HASH }}"

      - name: Lint Helm Chart
        run: helm lint helm

      - name: List Helm Directory
        run: ls -l helm

      - name: Show Chart.yaml
        run: cat helm/Chart.yaml

      - name: Show Current Directory
        run: pwd

      - name: List All Files
        run: ls -lah

      - name: List Git Files
        run: git ls-files

      - name: Show Git Status
        run: git status

      - name: Print Environment Variables
        run: env

      - name: Show Git Log
        run: git log -3 --oneline

      - name: Helm Version
        run: helm version

      - name: Package Helm Chart
        run: |
          VERSION="0.1.0-dev.${{ steps.vars.outputs.SHORT_HASH }}"
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+-dev\.[a-z0-9]+$ ]]; then
            echo "Invalid SemVer version string: $VERSION"
            exit 1
          fi
          helm package helm --version "$VERSION"
          mkdir -p helm-charts
          mv oomlet-*.tgz helm-charts/

      - name: Show helm-charts Contents
        run: ls -lh helm-charts

      - name: Output Packaged Chart Path
        run: |
          echo "Packaged chart:"
          ls helm-charts/*.tgz
