name: Helm Lint and Package Only

on:
  push:
    branches:
      - helm-lint-only
  workflow_dispatch:

jobs:
  helm:
    name: Helm Lint and Package (No Upload)
    runs-on: ubuntu-latest

    steps:
      - name: Set Git Short Hash
        id: vars
        run: echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Debug Git Short Hash
        run: echo "SHORT_HASH=${{ steps.vars.outputs.SHORT_HASH }}"

      - name: List Helm Directory
        run: ls -l helm

      - name: Show Chart.yaml
        run: cat helm/Chart.yaml

      - name: Helm Lint
        run: helm lint helm

      - name: Helm Package
        run: |
          SHORT_HASH=${{ steps.vars.outputs.SHORT_HASH }}
          helm package helm --version "0.1.0-dev.${SHORT_HASH}"
          mkdir -p helm-charts
          mv oomlet-*.tgz helm-charts/

      - name: Helm Version
        run: helm version