name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  maven-audit:
    name: Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22

      - name: Install OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check-8.4.0-release.zip -d dependency-check
          ./dependency-check/bin/dependency-check.sh --project "oomlet" --scan . --format HTML --out dependency-check-report.html

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html

  docker-audit:
    name: Docker Image Scan
    runs-on: ubuntu-latest
    needs: maven-audit

    steps:
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .