name: Security Scan

on:
  schedule:
    # Every Sunday at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  docker-audit:
    name: Docker Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy for config scan
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository_owner }}/oomlet:develop
          severity: HIGH,CRITICAL
          exit-code: 0
        continue-on-error: true

  code-scanning:
    name: Code Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build with Maven
        run: ./mvnw clean compile test-compile

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
