name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  maven-audit:
    name: Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22

      - name: Install OWASP Dependency-Check
        run: |
          mkdir -p dependency-check
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip -O dc.zip
          unzip -q dc.zip -d dependency-check
          ls dependency-check
          ./dependency-check/dependency-check/bin/dependency-check.sh --project "oomlet" --scan . --format HTML --out dependency-check-report.html

      - name: Export OWASP DC cache path
        run: echo "OWASP_DC_CACHE=/github/home/.dependency-check" >> $GITHUB_ENV

      - name: Also output SARIF report
        run: |
          ./dependency-check/bin/dependency-check.sh --project "oomlet" --scan . --format SARIF --out dependency-check-report.sarif

      - name: Upload SARIF report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report-sarif
          path: dependency-check-report.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: dependency-check-report.sarif

      - name: Upload security report HTML
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html

  docker-audit:
    name: Docker Image Scan
    runs-on: ubuntu-latest
    needs: maven-audit

    steps:
      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.14.0
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@0.14.0
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository_owner }}/oomlet/oomlet:latest
          severity: HIGH,CRITICAL
          exit-code: 1
